---
- name: update centos-release to latest
  package:
    name: centos-release
    state: latest

- name: install centos-opstools repo
  package:
    state: present
    name: centos-release-opstools

- name: install collectd
  package:
    state: present
    name: collectd

- name: install collectd-write-http
  package:
    state: present
    name: collectd-write_http
  when: use_collectd_exporter

- name: configure write_http
  copy:
    src: write_http.conf
    dest: /etc/collectd.d/write_http.conf
  when: use_collectd_exporter

- name: enable collectd-write-prometheus
  package:
    state: present
    name: collectd-write_prometheus
  when: not use_collectd_exporter

- name: load df plugin
  copy:
    src: df.conf
    dest: /etc/collectd.d/df.conf

- name: disable selinux if using collectd-write_prometheus
  selinux:
    state: permissive
    policy: targeted
  when: not use_collectd_exporter


# provide some sample plugins to generate output
- name: install collectd-disk
  package:
    state: present
    name: collectd-disk

- name: load disk plugin
  copy:
    src: disk.conf
    dest: /etc/collectd.d/disk.conf


- name: allow collectd to connect to network
  seboolean:
    name: collectd_tcp_network_connect
    state: yes
    persistent: yes
  when: ansible_selinux.status == "enabled"

- name: listen to connections on the net
  template:
    src: 10-network-listen.conf.j2
    dest: "/etc/collectd.d/10-network-listen.conf"
  when: collectd_network_listen

- name: start collectd
  service:
    name: collectd
    state: started
