---

- name: provision vm
  os_server:
    state: present
    auth:
      auth_url: "{{ lookup('env', 'OS_AUTH_URL') }}"
      username: "{{ lookup('env','OS_USERNAME') }}"
      password: "{{ lookup('env','OS_PASSWORD') }}"
      project_name: "{{ lookup('env','OS_TENANT_NAME') }}"
    name: '{{ node_name }}'
    image: '{{ os_image }}'
    flavor: '{{ os_flavor }}'
    key_name: "{{ lookup('env','OS_USERNAME') }}"
    terminate_volume: 'true'
    floating_ips:
      - '{{ node_ip }}'

- name: add node to inventory
  add_host:
    hostname: '{{ node_name }}'
    groups: deployment
    ansible_host: '{{ node_ip }}'
    ansible_user: 'centos'
    ansible_become: True

- name: remove node from ssh 
  known_hosts:
    state: absent
    name: '{{ node_ip }}'
