---

- name: pull alertmanager docker image
  docker_image:
    name: prom/alertmanager

- name: create prometheus-data dir
  file:
    state: directory
    path: /alertmanager-data
    mode: 0777

- name: place alertmanager config file
  template:
    src: alertmanager.yml.j2
    dest: /alertmanager-data/alertmanager.yml

- name: run alertmanager in docker
  docker_container:
    name: alertmanaer
    image: prom/alertmanager
    exposed_ports: 9093
    published_ports: 9093:9093
    volumes:
      - /alertmanager-data:/alertmanager-data:Z
    command: [ "--config.file=/alertmanager-data/alertmanager.yml",]

