---
- name: deploy docker
  package:
    name: docker
    state: present

- name: install docker-py
  package:
    name: python-docker-py
    state: present

- name: start and enable docker
  service:
    name: docker
    state: 'started'
    enabled: 'True'
